# golangci-lint configuration for terraform-provider-dotfiles
# Using the same linter configuration as ~/Development/club for consistency
version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  go: '1.25.1'

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  default: none
  enable:
    # Essential defaults that were disabled
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional table stakes linters
    - bodyclose
    - contextcheck
    - copyloopvar
    - depguard
    - dupl
    - errname
    - gocritic
    - gochecknoinits
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
          allow:
            # Standard library packages
            - "$gostd"
            # Project internal packages
            - "github.com/jamesainslie/terraform-provider-dotfiles"
            # Terraform provider framework and all sub-packages
            - "github.com/hashicorp/terraform-plugin-framework"
            - "github.com/hashicorp/terraform-plugin-framework/diag"
            - "github.com/hashicorp/terraform-plugin-framework/ephemeral"
            - "github.com/hashicorp/terraform-plugin-framework/function"
            - "github.com/hashicorp/terraform-plugin-framework/path"
            - "github.com/hashicorp/terraform-plugin-framework/provider"
            - "github.com/hashicorp/terraform-plugin-framework/provider/schema"
            - "github.com/hashicorp/terraform-plugin-framework/providerserver"
            - "github.com/hashicorp/terraform-plugin-framework/resource"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
            - "github.com/hashicorp/terraform-plugin-framework/schema/validator"
            - "github.com/hashicorp/terraform-plugin-framework/types"
            - "github.com/hashicorp/terraform-plugin-log"
            - "github.com/hashicorp/terraform-plugin-log/tflog"
            # Go git library
            - "github.com/go-git/go-git"
            # Other allowed dependencies
            - "github.com/stretchr/testify"
          deny:
            - pkg: github.com/pkg/errors
              desc: Please use "errors" package from standard library
    gocritic:
      disabled-checks:
        - ifElseChain
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104  # Errors unhandled
        - G301  # Poor file permissions
        - G302  # Poor file permissions
        - G304  # File path provided as taint input
        - G306  # Poor file permissions for WriteFile
        - G404  # Use of weak random number generator
    imports:
      alias:
        - pkg: github.com/stretchr/testify/assert
          alias: assert
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - tools$
    rules:
      - linters:
          - bodyclose
          - depguard
          - dupl
          - funlen
          - gochecknoglobals
          - goconst
          - gosec
          - gocritic
          - noctx
          - revive
          - wrapcheck
        path: _test\.go$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  exclude-dirs:
    - vendor
    - .git
    - bin
    - dist
    - tools

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - tools$
