# golangci-lint configuration for terraform-provider-dotfiles
# Updated to match golangci-lint v2 format for compatibility

version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  go: '1.25.1'

linters:
  default: none
  enable:
    # Essential defaults that were disabled
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional table stakes linters
    - bodyclose
    - contextcheck
    - copyloopvar
    - depguard
    - dupl
    - errname
    - gocritic
    - gochecknoinits
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
          allow:
            # Standard library packages
            - "$gostd"
            # Project internal packages - allow all internal imports
            - "github.com/jamesainslie/terraform-provider-dotfiles"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/errors"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/fileops"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/git"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/idempotency"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/migration"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/platform"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/provider"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/services"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/template"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/utils"
            - "github.com/jamesainslie/terraform-provider-dotfiles/internal/validators"
            # Terraform provider framework and all sub-packages
            - "github.com/hashicorp/terraform-plugin-framework"
            - "github.com/hashicorp/terraform-plugin-framework/diag"
            - "github.com/hashicorp/terraform-plugin-framework/ephemeral"
            - "github.com/hashicorp/terraform-plugin-framework/function"
            - "github.com/hashicorp/terraform-plugin-framework/path"
            - "github.com/hashicorp/terraform-plugin-framework/provider"
            - "github.com/hashicorp/terraform-plugin-framework/provider/schema"
            - "github.com/hashicorp/terraform-plugin-framework/providerserver"
            - "github.com/hashicorp/terraform-plugin-framework/resource"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
            - "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
            - "github.com/hashicorp/terraform-plugin-framework/schema/validator"
            - "github.com/hashicorp/terraform-plugin-framework/types"
            - "github.com/hashicorp/terraform-plugin-log"
            - "github.com/hashicorp/terraform-plugin-log/tflog"
            # Go git library
            - "github.com/go-git/go-git"
            # Other allowed dependencies
            - "github.com/stretchr/testify"
          deny:
            - pkg: github.com/pkg/errors
              desc: Please use "errors" package from standard library
    gocritic:
      disabled-checks:
        - ifElseChain
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104  # Errors unhandled
        - G301  # Poor file permissions
        - G302  # Poor file permissions
        - G304  # File path provided as taint input
        - G306  # Poor file permissions for WriteFile
        - G404  # Use of weak random number generator
    revive:
      rules:
        - name: package-comments
          disabled: true

  exclusions:
    generated: lax
    presets:
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - tools$
      - vendor
      - .git
      - bin
      - dist
    rules:
      - linters:
          - bodyclose
          - depguard
          - dupl
          - funlen
          - gochecknoglobals
          - goconst
          - gosec
          - gocritic
          - noctx
          - revive
          - wrapcheck
        path: _test\.go$

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jamesainslie/terraform-provider-dotfiles
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - tools$
