# Pre-commit hooks configuration for terraform-provider-dotfiles
# Install pre-commit: pip install pre-commit
# Install hooks: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Go formatting and imports
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy
      - id: go-vet
      - id: golangci-lint
        args: [--new-from-rev=HEAD~1]  # Only lint changed files

  # Local hooks using our Makefile targets
  - repo: local
    hooks:
      - id: make-pre-commit
        name: Make Pre-commit Checks
        entry: make
        args: [pre-commit]
        language: system
        files: \.go$
        pass_filenames: false
        stages: [pre-commit]

      - id: test-fast
        name: Fast Unit Tests
        entry: make
        args: [test-fast]
        language: system
        files: \.go$
        pass_filenames: false
        stages: [pre-push]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.md$'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key
      - id: check-executables-have-shebangs

  # Go security checks (temporarily disabled due to network issues)
  # - repo: local
  #   hooks:
  #     - id: gosec
  #       name: Go Security Scanner
  #       entry: gosec
  #       args: ['-fmt', 'text', './...']
  #       language: system
  #       files: \.go$
  #       pass_filenames: false

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']

  # Terraform formatting (for examples)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
        files: \.tf$
      - id: terraform_validate
        files: \.tf$

  # Spell checking
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
      - id: typos
        exclude: '\.git/|\.vscode/|node_modules/|\.terraform/'

  # Git commit message formatting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

# Configuration for specific hooks
default_language_version:
  python: python3

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
