# Security scanning workflow for terraform-provider-dotfiles
name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

# Security scanning needs permissions to write security events
permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  # Dependency vulnerability scanning
  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v6.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Set Go toolchain environment
        run: |
          echo "GOTOOLCHAIN=go1.25.1" >> $GITHUB_ENV
          echo "GOPROXY=https://proxy.golang.org,direct" >> $GITHUB_ENV

      - name: Download dependencies
        run: go mod download

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: |
          echo "Running govulncheck for vulnerability scanning..."
          set +e
          govulncheck -json ./... > govulncheck-report.json
          VULN_EXIT_CODE=$?

          # Display human-readable output
          echo "=== Vulnerability Report ==="
          govulncheck ./...

          if [ $VULN_EXIT_CODE -ne 0 ]; then
            echo "::warning::Vulnerabilities found by govulncheck (exit code: $VULN_EXIT_CODE)"
          else
            echo "::notice::No vulnerabilities found"
          fi

      - name: Upload govulncheck report
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always()
        with:
          name: govulncheck-report
          path: govulncheck-report.json
          retention-days: 30

  # Static security analysis
  security-analysis:
    name: Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v6.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Set Go toolchain environment
        run: |
          echo "GOTOOLCHAIN=go1.25.1" >> $GITHUB_ENV
          echo "GOPROXY=https://proxy.golang.org,direct" >> $GITHUB_ENV

      - name: Download dependencies
        run: go mod download

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec security scanner
        run: |
          echo "Running gosec security analysis..."
          set +e

          # Use same exclusions as golangci-lint for consistency
          GOSEC_EXCLUDES="-exclude=G104,G301,G302,G304,G306,G404"

          # Run SARIF generation (force success to generate report even with issues)
          gosec $GOSEC_EXCLUDES -fmt sarif -out gosec-report.sarif ./... || true
          SARIF_EXIT_CODE=$?
          if [ -f gosec-report.sarif ] && [ -s gosec-report.sarif ]; then
            echo "::notice::SARIF report generated successfully ($(wc -c < gosec-report.sarif) bytes)"
          else
            echo "::warning::SARIF generation produced empty/missing file, creating minimal report"
            echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"gosec","version":"unknown"}},"results":[]}]}' > gosec-report.sarif
          fi

          # Run JSON generation (force success to generate report even with issues)
          gosec $GOSEC_EXCLUDES -fmt json -out gosec-report.json ./... || true
          JSON_EXIT_CODE=$?
          if [ -f gosec-report.json ] && [ -s gosec-report.json ]; then
            echo "::notice::JSON report generated successfully ($(wc -c < gosec-report.json) bytes)"
          else
            echo "::warning::JSON generation produced empty/missing file"
          fi

          # Display human-readable output and determine overall status
          echo "=== Security Analysis Report ==="
          gosec $GOSEC_EXCLUDES ./...
          GOSEC_EXIT_CODE=$?

          if [ $GOSEC_EXIT_CODE -eq 0 ]; then
            echo "::notice::No security issues found"
          elif [ $GOSEC_EXIT_CODE -eq 1 ]; then
            echo "::warning::Security issues found by gosec - check reports for details"
          else
            echo "::error::gosec execution failed (exit code: $GOSEC_EXIT_CODE)"
          fi

      - name: Verify SARIF report
        run: |
          if [ -f gosec-report.sarif ] && [ -s gosec-report.sarif ]; then
            echo "::notice::SARIF file exists ($(wc -c < gosec-report.sarif) bytes)"
            # Basic validation - check if it's valid JSON
            if python3 -m json.tool gosec-report.sarif > /dev/null 2>&1; then
              echo "::notice::SARIF file is valid JSON"
            else
              echo "::warning::SARIF file is not valid JSON, but proceeding with upload"
            fi
          else
            echo "::warning::SARIF file is missing or empty, but workflow will continue"
          fi

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@6db8d6351fd0be61f9ed8ebd12ccd35dcec51fea # v3.26.11
        if: always() && hashFiles('gosec-report.sarif') != ''
        with:
          sarif_file: gosec-report.sarif
          category: gosec

      - name: Upload gosec reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always() && (hashFiles('gosec-report.sarif') != '' || hashFiles('gosec-report.json') != '')
        with:
          name: gosec-reports
          path: |
            gosec-report.sarif
            gosec-report.json
          retention-days: 30

  # CodeQL analysis
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v6.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Set Go toolchain environment
        run: |
          echo "GOTOOLCHAIN=go1.25.1" >> $GITHUB_ENV
          echo "GOPROXY=https://proxy.golang.org,direct" >> $GITHUB_ENV

      - name: Initialize CodeQL
        uses: github/codeql-action/init@6db8d6351fd0be61f9ed8ebd12ccd35dcec51fea # v3.26.11
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Download dependencies
        run: go mod download

      - name: Build Go packages for CodeQL analysis
        run: |
          echo "Building all Go packages for CodeQL analysis..."
          # Create output directory
          mkdir -p bin

          # Set build flags consistent with Makefile
          export GOFLAGS="-gcflags=all=-lang=go1.25"

          # Build all packages to ensure CodeQL can analyze them
          go build -v ./...

          # Build the main binary with version info
          VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
          COMMIT_HASH=$(git rev-parse HEAD 2>/dev/null || echo "unknown")

          go build -v -ldflags "-s -w -X main.version=${VERSION} -X main.commit=${COMMIT_HASH}" -o terraform-provider-dotfiles ./

          # Build the migrate-config tool
          go build -v -o bin/migrate-config ./cmd/migrate-config

          echo "Build completed successfully for CodeQL analysis"

      - name: Verify build outputs for CodeQL
        run: |
          echo "Verifying build outputs..."
          ls -la terraform-provider-dotfiles 2>/dev/null && echo "✓ Main binary built successfully" || echo "⚠ Main binary not found"
          ls -la bin/migrate-config 2>/dev/null && echo "✓ Migration tool built successfully" || echo "⚠ Migration tool not found"

          # Check if Go packages were compiled (look for .a files in build cache)
          echo "Checking Go build cache..."
          go list -f '{{.Target}}' ./... | head -5

          echo "Go environment for CodeQL:"
          go version
          go env GOARCH GOOS GOMOD GOWORK

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@6db8d6351fd0be61f9ed8ebd12ccd35dcec51fea # v3.26.11
        with:
          category: "/language:${{matrix.language}}"

  # License compliance check
  license-check:
    name: License Compliance
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v6.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install go-licenses
        run: go install github.com/google/go-licenses@latest

      - name: Check licenses
        run: |
          echo "Checking dependency licenses..."
          set +e
          go-licenses report ./... > license-report.txt
          LICENSE_EXIT_CODE=$?

          echo "=== License Report ==="
          cat license-report.txt

          # Check for forbidden licenses (customize as needed)
          if grep -E "(GPL|AGPL|LGPL)" license-report.txt; then
            echo "::error::Found copyleft licenses that may not be compatible"
            echo "Please review the licenses above"
            exit 1
          else
            echo "::notice::No problematic licenses found"
          fi

          if [ $LICENSE_EXIT_CODE -ne 0 ]; then
            echo "::warning::go-licenses exited with code $LICENSE_EXIT_CODE"
          fi

      - name: Upload license report
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always()
        with:
          name: license-report
          path: license-report.txt
          retention-days: 30

  # Security summary
  security-summary:
    name: Security Summary
    needs: [vulnerability-scan, security-analysis, codeql, license-check]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: security-reports/

      - name: Generate security summary
        run: |
          echo "# Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Job Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Vulnerability Scan: ${{ needs.vulnerability-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Security Analysis: ${{ needs.security-analysis.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- CodeQL Analysis: ${{ needs.codeql.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- License Check: ${{ needs.license-check.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Overall status
          if [[ "${{ needs.vulnerability-scan.result }}" == "success" &&
                "${{ needs.security-analysis.result }}" == "success" &&
                "${{ needs.codeql.result }}" == "success" &&
                "${{ needs.license-check.result }}" == "success" ]]; then
            echo "##  Overall Status: PASS" >> $GITHUB_STEP_SUMMARY
            echo "All security checks completed successfully." >> $GITHUB_STEP_SUMMARY
          else
            echo "##  Overall Status: ISSUES FOUND" >> $GITHUB_STEP_SUMMARY
            echo "One or more security checks found issues. Please review the reports." >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Available Reports" >> $GITHUB_STEP_SUMMARY
          echo "- Check the Security tab for SARIF reports" >> $GITHUB_STEP_SUMMARY
          echo "- Download artifacts for detailed JSON reports" >> $GITHUB_STEP_SUMMARY

          echo "Security scan completed at $(date)"
